### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by mauimoana** [zekarias-tilahun/cas2vec#1]
Hi, I generated a data set with the format you suggested, but it seems not working. Could you upload a sample data file with the format you use?  Great thanks.

**Comment by zekarias-tilahun** [comment]
Hi, Thank you for showing interest in our work.

I have added a dummy example in the ./data/train.txt file along with a readme file on the expected format of the input data.

**Comment by mauimoana** [comment]
Hi, Both the data format you suggested today and before can't work. I think the format you suggested before might be right. But it doesn't work for my implementation. Is the sample sequence too short? Could you upload your the processed Twitter or weibo sequence data.!
Thanks for your help.
![360截图20221012165756993](https://user-images.githubusercontent.com/77086328/195298404-2a1469d8-f53d-4e22-8662-00c8ceda34b9.jpg)

**Comment by zekarias-tilahun** [comment]
Hi, I don't think the error is related to the format of the data. As you can see from the log, the number of both viral and non-viral classes is 0. Unfortunately I don't have the code that I used to preprocess the twitter and weibo datasets into a cas2vec input format. I kindly suggest that you download the data from here http://snap.stanford.edu/seismic/ and parse it to cas2vec's input format.

**Comment by mauimoana** [comment]
Great thanks for your help. I'll try your suggestion later.

**Comment by zekarias-tilahun** [comment]
I have added a sample of 5000 cascades in data/train.txt extracted from the [Twitter dataset](http://snap.stanford.edu/seismic/) . The following is the preprocessing code used for generating the complete training data. To get the desired result during training, please make sure that you've the correct version of tensorflow.

```
import pandas as pd

data_url="http://snap.stanford.edu/seismic/data.csv"
index_url="http://snap.stanford.edu/seismic/index.csv"
data_df = pd.read_csv(data_url)
index_df = pd.read_csv(index_url)


cascades = []
for i, row in enumerate(index_df.itertuples()):
    content_df = data_df[row.start_ind-1:row.end_ind-1]
    events = content_df.relative_time_second.values
    users = content_df.number_of_followers.values
    cascades.append((i, users, events))
    
with open("data/train.txt", "w") as f:
    for cid, users, events in cascades:
        # users[i] is the degree not exactly a user id. It is just added as a place holder
        # it won't have any effect on training
        c = " ".join(f"{int(users[i])},{int(events[i])}"for i in range(len(users)))
        f.write(f"{cid} {c}\n")
```
